### ISSUE TITLE
Make it much more visible that we are in stealth mode

### ISSUE THREAD

**Issue by that0n3guy** [teleological/redmine_stealth#1]
Hey, awesome plugin.  One thing though is that we should probably have a more eyecatching visual indicator that shows that we are in stealth mode so we don't forget.

Maybe a simple 10px red bar above the site... super simple and would work w/ any theme.  Everytime you load a page you would see this red bar and know your in stealth mode.

**Comment by DS-BSZ** [comment]
+1

**Comment by teleological** [comment]
I think this is a good idea -- I sometimes forget that I'm in stealth mode and end up having to create follow-up emails. Would you be able to submit a pull request along the lines that you describe?

**Comment by teleological** [comment]
It looks like this person has a similar idea:

  https://gist.github.com/1025146/77e5c59d138948ebc654b0f7c82fdcaa620cccd0

**Comment by cs42** [comment]
This has at least one big problem: this code tests for the string which is internationalized, thus you would have to test for each language => not feasible

A better solution would be to add a class _stealth_on_ and _stealth_off_ to the HTML, preferably to the `<li>` of the menu entry or even better to the `<ul>` of the menu. There I'm failing currently...

**Comment by DS-BSZ** [comment]
It would be even better, if the highlighting was right where you enter your text, like e.g. a frame around the text box, or an indicator next to the OK button, when you update a ticket, etc.

**Comment by cs42** [comment]
Actually the best would be a `class=stealth_on` on the body of the page. All styling can then be done by the user. I just don't know how to do that...

**Comment by kfischer** [comment]
I think a class in the body tag is a great idea. We could style the page in a way that would make it very hard to miss that one is working in stealth mode and by this prevent a lot of problems from happening.

**Comment by cs42** [comment]
OK, I have a something on my fork: https://github.com/cs42/redmine-stealth-plugin/commit/d50e21982a69a3f242c0fd72f13c623e6a1d7190

This is not completely functional yet, as it doesn't set this class on clicking but only on loading the page. Thus you'll need to reload the page currently to see the changes.

**Comment by teleological** [comment]
This was fixed by Carsten's patch, version 0.3.0.
