### ISSUE TITLE
NoMethodError in Welcome#index

### ISSUE THREAD

**Issue by mashit** [teleological/redmine_stealth#11]
I am getting following error after installing the plugin. 

Showing app/views/layouts/base.html.erb where line #25 raised:

undefined method `+' for nil:NilClass

my redmine version is 1.3.0

please provide some guidance on how to solve this issue.

**Comment by teleological** [comment]
Are you using any other plugins? It sounds like body_css_classes may be returning nil.

**Comment by mashit** [comment]
yes i using few other plugins

**Comment by ey123** [comment]
Same problem here.

Redmine 1.3
body_css_classes returns nil.

No other plugin uses body_css_classes
Please advise

Thanks,
Eyal

**Comment by teleological** [comment]
Does the latest commit resolve the issue?

**Comment by teleological** [comment]
I think this was fixed in ad42f285624e6bf9f24c6986ac26cf7757d9bf95, but please reopen if you find otherwise.
