### ISSUE TITLE
Error in call hook

### ISSUE THREAD

**Issue by LuisSerrano** [teleological/redmine_stealth#13]
The plugin returns this error (Redmine 1.3.2 without plugins)

NoMethodError in Issues#show

Showing app/views/issues/show.html.erb where line #45 raised:

undefined method `call_hook' for #ActionView::Base:0x7ff02dc8c650
Extracted source (around line #45):

42:     <% end %>
43: </tr>
44: <%= render_custom_fields_rows(@issue) %>
45: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
46: </table>
47: 
48: <% if @issue.description? || @issue.attachments.any? -%>

**Comment by teleological** [comment]
Do you see an indication that this issue is related to the plugin? Neither the call_hook method, nor :view_issues_show_details_bottom are referenced by the plugin code.

**Comment by teleological** [comment]
Closing for want of response, but please feel free to open if the problem persists.
