### ISSUE TITLE
Translation NL missing

### ISSUE THREAD

**Issue by hitzel** [teleological/redmine_stealth#17]
translation missing: en.failed_to_toggle_stealth_mode

**Comment by euriehong** [comment]
When you click on that message to toggle stealth_mode, says "translation missing: en.failed_to_toggle_stealth_mode" even if you have permission to toggle it.

**Comment by teleological** [comment]
I think this is because there is not yet a Dutch translation of the messages. We should probably make it default to English, but on the other hand, this kind of error message has resulted in a number of translations being submitted. :)

**Comment by teleological** [comment]
This may be related to issue #19. Testing if the suggested fix results in the english translations being used as defaults.

**Comment by teleological** [comment]
I was able to replicate: This appears to be the same issue as #19, affecting installations where the plugin is not installed in "plugins/redmine-stealth-plugin". Closing this issue since #19 has more details.

**Comment by teleological** [comment]
I've found a second issue: The menu item is registered with text before the plugin translation catalog is loaded. Reopening until that is fixed.

**Comment by teleological** [comment]
Fixed in v0.6.0
