### ISSUE TITLE
With Redmine 2.0.3. Translation missing in spite of language set to English

### ISSUE THREAD

**Issue by Sethur** [teleological/redmine_stealth#19]
I just updated Redmine to 2.0.3 and installed the plugin as described via git clone. I then assigned toggle permissons to the manager role and tried to turn on the Stealth mode. Although both my default language and the current language of the user I was using to test the plugin is set to "English", I only get "translation missing: en.enable_stealth_mode" at the status bar, and when I click that I get "translation missing: en_failed_to_toggle_stealth_mode". So obviously, something went completely wrong when installing / initializing the plugin, but I have no idea what. I restarted apache and passenger several times and the language files for the "missing" translation seem to be present, too. Any ideas?

**Comment by Robbedoes33** [comment]
Fixed this by renaming the directory to redmine_stealth 
And changed line 10 of stealth_hooks.rb to :plugin => 'redmine_stealth'

**Comment by ramisedhom** [comment]
It works after doing Rob suggestion but it need to be restarted after doing those changes.

**Comment by teleological** [comment]
It looks like the problem occurs if the plugin is not installed in "plugins/redmine-stealth-plugin". This is the location recommended in the install instructions, but the fact that the plugin registers itself as "redmine_stealth" muddies the water. I'll go ahead and rename the plugin and repository "redmine_stealth" in the next release.

**Comment by teleological** [comment]
Fixed in v0.6.0
