### ISSUE TITLE
Stealth changes not visible in Activity

### ISSUE THREAD

**Issue by xadh00m** [teleological/redmine_stealth#22]
Hi,

I´m using the latest version 0.6.0 with Redmine 2.1.2. When making ticket updates in stealth mode there is no entry added to the list of project acitivites. Is this an intended behaviour?

Actually we would be interested to still be able to track changes made in stealth mode via the activity log. Could this be added as an optional setting?

Regards,
xad

**Comment by teleological** [comment]
The intention of stealth mode is only to stifle emails. If you have a chance to investigate the cause of supressed activity logging, please let me know what you learn!

**Comment by xadh00m** [comment]
Thanks for your reply. I just investigated further and figured out that this is unrelated to the stealth plugin and only happens for issue updates without additional text (like setting custom fields only, which emit notifications though). I accidentally thought of a plugin issue here. In all the years I never recognized that this activity view behavior of redmine is "intended".

Sorry for the inconvenience,
xad

**Comment by teleological** [comment]
Thank you for the follow-up!
