### ISSUE TITLE
Label text won't replaced through text 

### ISSUE THREAD

**Issue by tuxinaut** [teleological/redmine_stealth#4]
Hello

the error message MESSAGE_TOGGLE_FAILED (label failed_to_toggle_stealth_mode) won't replaced through text.

![Error](http://i39.tinypic.com/fxfosy.png)

**Comment by teleological** [comment]
I assume this was a result of using the plugin before the German translation was added? Closing, but please feel free to reopen if the problem persists.

**Comment by tuxinaut** [comment]
Still exists. And i cant reopen the issue

**Comment by teleological** [comment]
Ok, will look at it soon. For the time being, I recommend v0.1.0 as the stable version before the translations and css support were added.

**Comment by teleological** [comment]
MESSAGE_TOGGLE_FAILED constant is being passed directly into JavaScript without being looked up in the message catalog. Fixing in v0.4.0.
